apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wandelen
  namespace: wandelen
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: wandelen.carpago.nl
      http:
        paths:
          - backend:
              service:
                name: wandelen-api
                port:
                  number: 8080
            path: /(.*api.*|.*swagger.*)
            pathType: Prefix
          - backend:
              service:
                name: wandelen-ui
                port:
                  number: 8080
            path: /
            pathType: Prefix
