apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wandelen
  namespace: wandelen
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/issuer: letsencrypt-nginx
spec:
  tls:
    - hosts:
      - wandelen.carpago.nl
      secretName: letsencrypt-nginx-wandelen
  ingressClassName: nginx
  rules:
    - host: wandelen.carpago.nl
      http:
        paths:
          - backend:
              service:
                name: wandelen-api
                port:
                  number: 8080
            path: /(.*api.*|.*swagger.*)
            pathType: Prefix
          - backend:
              service:
                name: wandelen-ui
                port:
                  number: 8080
            path: /
            pathType: Prefix
