apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: wandelen
spec:
  #storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
